servers:
  - url: https://dev-share-video.herokuapp.com/

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${JDBC_DATASOURCE_URL}
    username: postgres
    password: Nmasjk.100
    driver-class-name: org.postgresql.Driver





